### ISSUE TITLE
[feature] add Backend for AWS Secrets Manager

### ISSUE THREAD

**Issue by emicklei** [kramphub/kiya#29]
I propose to extend kiya such that it becomes a multi-cloud solution for easy access to secrets.
One such extension would be to support access to secrets in AWS.
Thanks to the recent refactoring, it should be a simple task to support AWS as a backend

**Comment by emicklei** [comment]
@amohabir wdyt

**Comment by amohabir** [comment]
If someone wants to implement it, go for it! I don't have any experience with AWS' secrets manager.

**Comment by ghost** [comment]
Currently, the secret manager costs are quite high (about 10 times that of GCP).
So instead, we could use the KMS and S3 services of AWS just like the non-GSM approach of the early kiya design.
For AWS, the first 20.000 KMS calls are free and storage in S3 is also cheap.
